INSERT INTO albumfotografico.photo(title, description, tag, url, visible) VALUES('Monte Bianco', "la montagna più bianca", "montagna", 'https://picsum.photos/200/150', true);
INSERT INTO albumfotografico.photo(title, description, tag, url, visible) VALUES('Zozzomarina', 'il mare pulito', "mare", 'https://picsum.photos/200/150', false);
INSERT INTO albumfotografico.photo(title, description, tag, url, visible) VALUES('New York', 'la grande mela', "metropoly", 'https://picsum.photos/200/150', true);
INSERT INTO albumfotografico.category(name) VALUES('viaggiare');
INSERT INTO albumfotografico.category(name) VALUES('città');
INSERT INTO albumfotografico.category(name) VALUES('moda');
INSERT INTO albumfotografico.category(name) VALUES('tecnologia');
INSERT INTO albumfotografico.category_photo(photo_id, category_id) VALUES(1,1);
INSERT INTO albumfotografico.category_photo(photo_id, category_id) VALUES(2,1);
INSERT INTO albumfotografico.category_photo(photo_id, category_id) VALUES(3,2);
INSERT INTO albumfotografico.category_photo(photo_id, category_id) VALUES(3,3);